### ISSUE TITLE
`token_required` decorator does not work correctly on instance methods

### ISSUE THREAD

**Issue by jkorinth** [app-generator/api-server-flask#13]
The `current_user` is passed into the decorated function first, switching places with `self`:

https://github.com/app-generator/api-server-flask/blob/748432027dcdb512cf76a6b45100db2c2c3ef1eb/api/routes.py#L76

A possible fix would be to retain the first param in the inner decorator function:
```python3
def token_required(f):
    @wraps(f)
    def decorator(ref, *args, **kwargs):
         ...
         # call with ref
         return f(ref, current_user, *args, **kwargs)
```

But this will fail on regular functions. Probably `inspect` could be used to make it general.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
