### ISSUE TITLE
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' 

### ISSUE THREAD

**Issue by rickspencer3** [app-generator/api-server-flask#14]
It looks like the latest version of this library doesn't work with the application. I get this error when I run the tests. 

I am not very familiar with the Python packaging and testing frameworks, so I could be doing something wrong.

**Comment by rickspencer3** [comment]
I see that in the requirements.txt the werkzeyg package has been pinned to an earlier version, presumably to work round this issue

**Comment by rickspencer3** [comment]
Ok, I figured out my confusion, the docker-compose is not for development

**Comment by app-generator** [comment]
Hello @rickspencer3 

All good now? 

We just did a quick test and the API works as expected.
